"""add column telefone in OS table

Revision ID: 831d778af154
Revises: 6203ca654277
Create Date: 2025-08-09 12:37:05.988151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831d778af154'
down_revision: Union[str, Sequence[str], None] = '6203ca654277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('os', sa.Column('telefone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('os', 'telefone')
    # ### end Alembic commands ###
