"""create os table

Revision ID: 6203ca654277
Revises: 
Create Date: 2025-08-09 12:33:38.284932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6203ca654277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=False),
    sa.Column('entrega', sa.String(), nullable=False),
    sa.Column('entregue', sa.Enum('sim', 'nao', name='entregue'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('os')
    # ### end Alembic commands ###
